[package]
name = "wcr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
duplicate = "0.4.1"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8.0"